knpu_oauth2_client:
    clients:
      google:
        type: google
        client_id: '%env(OAUTH_GOOGLE_ID)%'
        client_secret: '%env(OAUTH_GOOGLE_SECRET)%'
        redirect_route: connect_google_callback
        redirect_params: { }
      twitch:
        type: twitch
        client_id: '%env(OAUTH_TWITCH_ID)%'
        client_secret: '%env(OAUTH_TWITCH_SECRET)%'
        redirect_route: connect_twitch_callback
        redirect_params: { }

